/*

SQOL
DDL : Data  Defination Language => Datanýn tanýmlanmasý ile ilgili
Veri tabaný objesini (tablo,storprosedür,funcion,wiev) oluþturmak silmek güncellemek

DML : Data Manupilation Language => Datanýn 

*/
--USE MSSQLCourseDb
--go
------------------- DLL


--CREATE TABLE Persons
--(
--    Id INT,
--	FirstName NVARCHAR(50),
--	LastName NVARCHAR(50),
--	Age TINYINT
--)

--DROP TABLE Persons

--CREATE TABLE Persons
--(
--Id INT PRIMARY KEY IDENTITY(1,1),
--FirstName NVARCHAR(50) NOT NULL,
--LastName NVARCHAR(50) NOT NULL,
--Age TINYINT
--)

--CREATE TABLE Persons
--(
--Id INT ,
--FirstName NVARCHAR(50) NOT NULL,
--LastName NVARCHAR(50) NOT NULL,
--Age TINYINT
--CONSTRAINT PK_Persons PRIMARY KEY (Id)
--)

--CREATE TABLE Persons
--(
--Id INT ,
--FirstName NVARCHAR(50) NOT NULL,
--LastName NVARCHAR(50) NOT NULL,
--Age TINYINT
---- AYNI ÝSÝMDE VE AYNI SOYÝSÝMDE 2 KÝÞÝYÝ KAYDEDEMEZSÝN
--CONSTRAINT PK_Persons PRIMARY KEY (FirstName,LastName)
--)

--CREATE TABLE Persons
--(
--Id INT PRIMARY KEY IDENTITY(1,1) ,
--FirstName NVARCHAR(50) NOT NULL,
--LastName NVARCHAR(50) NOT NULL,
--Age TINYINT,
---- CHEK CONSTRAINT O KOLONA O ALANA GÝRÝLECEK OLAN DATAYI KONTROL EDER
--TCNO CHAR(11),
--CHECK(LEN(TCNO)=11)
--)

-- AGE 18 DEN BÜYÜK OLSUN
--CREATE TABLE Persons
--(
--Id INT PRIMARY KEY IDENTITY(1,1) ,
--FirstName NVARCHAR(50) NOT NULL,
--LastName NVARCHAR(50) NOT NULL,
--Age TINYINT,
--CHECK(Age>18),
--TCNO CHAR(11),
--CHECK(LEN(TCNO)=11)
--)

-- BÝZ DEÐER YAZMAZSAK DEFAULT DEÐER YAZSIN

CREATE TABLE Persons
(
Id INT PRIMARY KEY IDENTITY(1,1) ,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Age TINYINT,
TCNO CHAR(11),
RegisterDate DATETIME DEFAULT GETDATE()
)

-- TABLOYU DEÐÝÞTÝRME
-- AGE YÝ NOTT NULL YAPACAZ
-- ALTER KOMUTUNU KULLANICAZ  CREATE EKLE DROP SÝL ALTER GÜNCELLE
ALTER TABLE Persons
ALTER COLUMN Age TINYINT NOT NULL

-- GÜNCELLEYEREK CONSTRAINT YAZABÝLÝRÝZ

ALTER TABLE Persons -- TABLOYU GÜNCELLÝYCEM
ADD CONSTRAINT UC_TCNO UNIQUE (TCNO) -- TABLOYA UC_TCNO ADINDA UNIQUE TÝPÝNDE CONSTRAINT EKLÝYORUM TCNO ALANINA
--00:42:51




